fos_comment_comment_create:
    pattern:        /comment/new/{threadId}/{parentId}
    defaults:       { _controller: FOSCommentBundle:Comment:create, parentId: null }
    requirements:   { _method: "post" }

fos_comment_thread_show_feed:
    pattern:        /{id}.xml
    defaults:       { _controller: FOSCommentBundle:Thread:showFeed, _format: xml }
