doctrine_user_user_list:
    pattern:    /people
    defaults:   { _controller: DoctrineUserBundle:User:list }

doctrine_user_user_new:
    pattern:    /signup
    defaults:   { _controller: DoctrineUserBundle:User:new, _method: get }

doctrine_user_user_create:
    pattern:    /signup
    defaults:   { _controller: DoctrineUserBundle:User:new, _method: post }

doctrine_user_user_show:
    pattern:    /@/:username
    defaults:   { _controller: DoctrineUserBundle:User:show }
