lichess_translation_contribution:
    pattern:        /contribute
    defaults:       { _controller: LichessTranslationBundle:Contribution:index}
lichess_translation_contribution_locale:
    pattern:        /contribute/{locale}
    defaults:       { _controller: LichessTranslationBundle:Contribution:locale}
    requirements:   { locale: "\w{2,3}" }
lichess_translation_contribution_export:
    pattern:        /contribute/export.json
    defaults:       { _controller: LichessTranslationBundle:Contribution:export, _format: json }
