forum_index:
    pattern:        /forums
    defaults:       { _controller: ForumBundle:Forum:index }
    requirements:   { _method: get }

forum_search:
    pattern:        /forums/search
    defaults:       { _controller: ForumBundle:Forum:search }
    requirements:   { _method: get, slug: "[\w-]+" }

forum_category:
    resource: ForumBundle/Resources/config/routing/category.xml
    prefix:     /forum

forum_topic:
    resource: ForumBundle/Resources/config/routing/topic.xml
    prefix:     /forum

forum_post:
    resource: ForumBundle/Resources/config/routing/post.xml
    prefix:     /forum
