doctrine_user_user_list:
    pattern:    /people
    defaults:   { _controller: doctrine_user.controller.user:listAction }

doctrine_user_user_new:
    pattern:    /signup
    defaults:   { _controller: doctrine_user.controller.user:newAction }
    requirements: { _method: get }

doctrine_user_user_create:
    pattern:    /signup
    defaults:   { _controller: doctrine_user.controller.user:createAction }
    requirements: { _method: post }

doctrine_user_user_show:
    pattern:    /@/:username
    defaults:   { _controller: doctrine_user.controller.user:showAction }

doctrine_user_user_confirmed:
    pattern:    /signup-confirmed
    defaults:   { _controller: doctrine_user.controller.user:confirmedAction }
