fos_user_online:
    pattern:    /ping/:username
    defaults:   { _controller: fos_user.controller.user:onlineAction }
    requirements: { _method: get }

fos_user_user_list:
    pattern:    /people
    defaults:   { _controller: fos_user.controller.user:listAction }
    requirements: { _method: get|head }

fos_user_user_new:
    pattern:    /signup
    defaults:   { _controller: fos_user.controller.user:newAction }
    requirements: { _method: get }

fos_user_user_create:
    pattern:    /signup
    defaults:   { _controller: fos_user.controller.user:createAction }
    requirements: { _method: post }

fos_user_user_show:
    pattern:    /@/:username
    defaults:   { _controller: fos_user.controller.user:showAction }
    requirements: { _method: get|head }

fos_user_user_confirmed:
    pattern:    /signup-confirmed
    defaults:   { _controller: fos_user.controller.user:confirmedAction }
