imports:
    - { resource: config.yml }

twig:
    exception_controller: LichessBundle:Exception:show

doctrine_mongodb:
    default_database: lichess

assetic:
    debug: false

lichess:
    ai:
        crafty:
            executable_path: /usr/games/crafty

fos_comment:
    service:
        spam_detection:
            comment: fos_comment.spam_detection.comment.akismet
