framework:
    secret: oUGAVIjf5zG2O6WJkwI7
    charset:       UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enable_annotations: true }
    form:            true
    esi: false
    csrf_protection: false
    session:
        default_locale: en
        name:     lichess2
        lifetime: 72000
        auto_start:     true
    templating:
        assets_version: 18
        engines: ['twig']
    translator: { fallback: en }
