fos_user_online_users:
    pattern:    /online-users
    defaults:   { _controller: FOSUserBundle:Online:listOnline }

fos_user_online_update:
    pattern:    /update-online-users
    defaults:   { _controller: FOSUserBundle:Online:updateOnline }
    requirements: { _method: post }
