fos_user_user_list:
    pattern:    /people
    defaults:   { _controller: FOSUserBundle:Profile:list }

fos_user_user_show:
    pattern:    /@/{username}/{mode}
    defaults:   { _controller: FOSUserBundle:Profile:view, mode: all }

fos_user_autocomplete:
    pattern:    /autocomplete-user
    defaults:    { _controller: FOSUserBundle:Profile:autocomplete }

fos_user_profile_update:
    pattern:    /profile/update.json
    defaults:   { _controller: FOSUserBundle:Profile:updateProfile }
    requirements: { _method: post }

fos_user_close_account:
    pattern:    /profile/close
    defaults:   { _controller: FOSUserBundle:Profile:closeAccount }

fos_user_profile_bio:
    pattern:    /profile/bio
    defaults:   { _controller: FOSUserBundle:Profile:profileBio }
