imports:
    - { resource: config.yml }

framework:
    exception_controller: LichessBundle:Exception:show

doctrine_mongo_db:
    default_database: lichess

lichess:
    ai:
        crafty:
            executable_path: /usr/games/crafty

fos_comment:
    service:
        spam_detection:
            comment: fos_comment.spam_detection.comment.akismet

apc:
    host: lichess.org
    web_dir: %kernel.root_dir%/../web
