app.config:
    charset:             UTF-8
    error_handler_level: null
    validation: { enabled: true, annotations: false }
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    user:
        lifetime: 2592000 # one month 
    templating:
        escaping: false
        assets_version: 58

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log

lichess.config:
    ai:
        class: Bundle\LichessBundle\Ai\Stupid # also available: Bundle\LichessBundle\Ai\Stupid
