imports:
    - { resource: config.yml }

webprofiler.config:
    toolbar: true
    intercept_redirects: false

app.config:
    profiler:
        only_exceptions: false

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log
