imports:
    - { resource: config.yml }

framework:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        only_exceptions: true

web_profiler:
    toolbar: false
    intercept_redirects: false

zend:
    logger:
        priority: NOTICE
        path:     %kernel.logs_dir%/%kernel.environment%.log

lichess:
    debug_assets: true
    sync:
        path: /xhr_dev.php

apc:
    host: lichess

lichess_forum:
    detect_spam: false

lichess_message:
    detect_spam: false
