imports:
    - { resource: config.yml }

framework:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

zend:
    logger:
        priority: INFO
        path:     %kernel.logs_dir%/%kernel.environment%.log

twig:
    auto_reload: true

doctrine_mongo_db:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    metadata_cache_driver: array
    cache_driver: array
    default_database: lichess_dev
    connections:
        default:
            options:
                connect: true
                persist: lichess_dev

lichess:
    debug_assets: true

lichess_forum:
    detect_spam: true
