app.config:
    charset:       UTF-8
    error_handler: null
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: true, annotations: true }
    csrf_protection:
        enabled: true
    session:
        default_locale: en
        name:     SF
        type:     Native
        lifetime: 2592000
    templating:
        escaping: htmlspecialchars
        assets_version: 121
        engines: ['twig']
    translator: { fallback: en }

zend.config:
    logger:
        priority: NOTICE
        path:     %kernel.logs_dir%/%kernel.environment%.log

twig.config: ~

apc.config:
    host: http://lichess.org
    web_dir: %kernel.root_dir%/../web

doctrine_odm.mongodb:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false
    default_database: lichess
    metadata_cache_driver: apc
    cache_driver: apc
    mappings:
        LichessBundle: ~
        FOSUserBundle: ~
        LichessUserBundle: ~
        OrnicarMessageBundle: ~
        LichessMessageBundle: ~
        ForumBundle:
        LichessForumBundle:
    connections:
        default:
            options:
                connect: true
                persist: lichess

forum.config:
    db_driver: odm
    class:
        model:
            category: Application\ForumBundle\Document\Category
            topic: Application\ForumBundle\Document\Topic
            post: Application\ForumBundle\Document\Post
        controller:
            topic: Application\ForumBundle\Controller\TopicController
            post: Application\ForumBundle\Controller\PostController
        form:
            post: Application\ForumBundle\Form\PostForm
            first_post: Application\ForumBundle\Form\PostForm
        blamer:
            post: Application\ForumBundle\Blamer\PostBlamer
        twig:
            extension: Application\ForumBundle\Twig\ForumExtension
    paginator:
        topics_per_page: 10
        posts_per_page: 10
        search_results_per_page: 10

lichess_user.config: ~

security.config:
    providers:
        fos_user:
            password_encoder: sha1
            document:
                class: Application\UserBundle\Document\User
                property: usernameCanonical
    firewalls:
        public:
            pattern: .*
            form_login:
                provider:                       fos_user
                login_path:                     /login
                use_forward:                    false
                check_path:                     /login-check
                failure_path:                   null
            logout: true
            anonymous: true
    access_control:
        - { path: "/inbox.*", role: IS_AUTHENTICATED_FULLY }
        - { path: "/.*", role: IS_AUTHENTICATED_ANONYMOUSLY }

fos_user.config:
    db_driver: mongodb
    encoder:
        iterations: 1
        encodeHashAsBase64: false
    class:
        model:
            user: Application\UserBundle\Document\User
        form:
            user: Application\UserBundle\Form\UserForm
        controller:
            user: Application\UserBundle\Controller\UserController
            security: Application\UserBundle\Controller\SecurityController

ornicar_message.config:
    db_driver: odm
    class:
        model:
            message: Application\MessageBundle\Document\Message

lichess_message.config: ~

time.config: ~

lichess.config:
    db_driver: odm
    ai:
        class: Bundle\LichessBundle\Ai\Crafty # also available: Bundle\LichessBundle\Ai\Stupid
    storage:
        class: Bundle\LichessBundle\Storage\Apc
