web.session:
    lifetime: 2592000 # one month 

web.config:
    charset:             UTF-8
    error_handler_level: null
    validation: { enabled: false }
    router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating:
    escaping: false

lichess.config: ~
