imports:
    - { resource: config.yml }

webprofiler.config:
    toolbar: false
    intercept_redirects: false

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log
