app.config:
    charset:             UTF-8
    error_handler: null
    validation: { enabled: true, annotations: true }
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    session:
        lifetime: 2592000 # one month 
    templating:
        escaping: htmlspecialchars
        assets_version: 121
    translator: { fallback: en }

zend.config:
    logger:
        priority: NOTICE
        path:     %kernel.logs_dir%/%kernel.environment%.log

twig.config: ~

apc.config:
    host: http://lichess.org
    web_dir: %kernel.root_dir%/../web

doctrine_odm.mongodb:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false
    default_database: lichess
    metadata_cache_driver: apc
    cache_driver: apc
    mappings:
        LichessBundle: ~
        UserBundle:
            type: xml
            dir: %kernel.root_dir%/../src/Bundle/FOS/UserBundle/Resources/config/doctrine/metadata/mongodb
            prefix: Bundle\FOS\UserBundle\Document
        AppUserBundle:
            type: annotation
            dir: %kernel.root_dir%/../src/Application/UserBundle/Document
            prefix: Application\UserBundle\Document
        MessageBundle:
            type: xml
            dir: %kernel.root_dir%/../src/Bundle/Ornicar/MessageBundle/Resources/config/doctrine/metadata/mongodb
            prefix: Bundle\Ornicar\MessageBundle\Document
        AppMessageBundle:
            type: annotation
            dir: %kernel.root_dir%/../src/Application/MessageBundle/Document
            prefix: Application\MessageBundle\Document
        ForumBundle:
            type: xml
            dir: %kernel.root_dir%/../src/Bundle/ForumBundle/Resources/config/doctrine/metadata/mongodb
            prefix: Bundle\ForumBundle\Document
        AppForumBundle:
            type: annotation
            dir: %kernel.root_dir%/../src/Application/ForumBundle/Document
            prefix: Application\ForumBundle\Document
    connections:
        default:
            options:
                connect: true
                persist: lichess

forum.config:
    db_driver: odm
    class:
        model:
            category: Application\ForumBundle\Document\Category
            topic: Application\ForumBundle\Document\Topic
            post: Application\ForumBundle\Document\Post
        controller:
            topic: Application\ForumBundle\Controller\TopicController
            post: Application\ForumBundle\Controller\PostController
        form:
            post: Application\ForumBundle\Form\PostForm
            first_post: Application\ForumBundle\Form\PostForm
        blamer:
            post: Application\ForumBundle\Blamer\PostBlamer
        helper:
            forum: Application\ForumBundle\Templating\Helper\ForumHelper
    paginator:
        topics_per_page: 10
        posts_per_page: 10
        search_results_per_page: 10

fos_user.config:
    db_driver: mongodb
    encoder:
        iterations: 1
        encodeHashAsBase64: false
    class:
        model:
            user: Application\UserBundle\Document\User
        form:
            user: Application\UserBundle\Form\UserForm
        controller:
            user: Application\UserBundle\Controller\UserController
            security: Application\UserBundle\Controller\SecurityController

fos_user_custom.config: ~

security.config:
    providers:
        fos_user:
            password_encoder: sha1
            id: fos_user.user_manager
    firewalls:
        public:
            pattern: .*
            form_login:
                provider:                       fos_user
                login_path:                     /login
                use_forward:                    false
                check_path:                     /login-check
                failure_path:                   null
            logout: true
            anonymous: true
    access_control:
        - { path: "/inbox.*", role: IS_AUTHENTICATED_FULLY }
        - { path: "/.*", role: IS_AUTHENTICATED_ANONYMOUSLY }

ornicar_message.config:
    db_driver: odm
    class:
        model:
            message: Application\MessageBundle\Document\Message

app_ornicar_message.config: ~

time.config: ~

lichess.config:
    db_driver: odm
    ai:
        class: Bundle\LichessBundle\Ai\Crafty # also available: Bundle\LichessBundle\Ai\Stupid
    storage:
        class: Bundle\LichessBundle\Storage\Apc
