app.config:
    charset:             UTF-8
    error_handler_level: null
    validation: { enabled: true, annotations: false }
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    user:
        lifetime: 2592000 # one month 
    templating:
        escaping: false
        assets_version: 74

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log

apc.config:
    host: http://lichess.org
    web_dir: %kernel.root_dir%/../web

time.helper: ~

lichess.config:
    ai:
        class: Bundle\LichessBundle\Ai\Crafty # also available: Bundle\LichessBundle\Ai\Stupid
