imports:
    - { resource: config.yml }

webprofiler.config:
    toolbar: true
    intercept_redirects: false

doctrine_odm.mongodb:
    metadata_cache_driver: array
    cache_driver: array

app.config:
    profiler:
        only_exceptions: false

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log
