framework:
    charset:       UTF-8
    error_handler: null
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: true, annotations: true }
    csrf_protection:
        enabled: false
    session:
        default_locale: en
        name:     lichess1
        lifetime: 15552000 # 6 months
        auto_start:     true
    templating:
        assets_version: 14
        engines: ['twig']
    translator: { fallback: en }

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

zend:
    logger:
        priority: NOTICE
        path:     %kernel.logs_dir%/%kernel.environment%.log

apc:
    host: http://lichess.org
    web_dir: %kernel.root_dir%/../web

doctrine_mongo_db:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persist: lichess
    default_database: lichess
    document_managers:
        default:
            mappings:
                LichessBundle: ~
                FOSUserBundle: ~
                LichessUserBundle: ~
                OrnicarMessageBundle: ~
                LichessMessageBundle: ~
                ForumBundle:
                LichessForumBundle:
            metadata_cache_driver: apc

forum:
    db_driver: odm
    class:
        model:
            category: Application\ForumBundle\Document\Category
            topic: Application\ForumBundle\Document\Topic
            post: Application\ForumBundle\Document\Post
        controller:
            topic: Application\ForumBundle\Controller\TopicController
            post: Application\ForumBundle\Controller\PostController
        form:
            post: Application\ForumBundle\Form\PostForm
            first_post: Application\ForumBundle\Form\PostForm
        blamer:
            post: Application\ForumBundle\Blamer\PostBlamer
        twig:
            extension: Application\ForumBundle\Twig\ForumExtension
    paginator:
        topics_per_page: 10
        posts_per_page: 10
        search_results_per_page: 10

lichess_forum:
    detect_spam: true

security:
    providers:
        fos_user_provider:
            id: fos_user.user_manager
    firewalls:
        main:
            form_login:
                provider:    fos_user_provider
                login_path:  /login
                check_path:  /login_check
                use_referer: true
            remember_me:
                key:  kRopAjYEwDza74
                name: lichess_remember_me
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout: true
            anonymous: true
    access_control:
        - { path: "/inbox.*", role: IS_AUTHENTICATED_FULLY }
        - { path: "/forum/(post|topic)/delete/.+", role: IS_SUPERADMIN }

fos_user:
    db_driver: mongodb
    provider_key: main
    encoder:
        iterations: 1
        encode_as_base64: false
        algorithm: sha1
    class:
        model:
            user: Application\UserBundle\Document\User
            group: FOS\UserBundle\Document\DefaultGroup
        form:
            user: Application\UserBundle\Form\UserForm
        controller:
            user: Application\UserBundle\Controller\UserController
            security: Application\UserBundle\Controller\SecurityController

lichess_user: ~

ornicar_message:
    db_driver: odm
    class:
        model:
            message: Application\MessageBundle\Document\Message
        controller:
            message: Application\MessageBundle\Controller\MessageController

lichess_message:
    detect_spam: true

lichess:
    ai:
        class: Bundle\LichessBundle\Ai\Crafty # also available: Bundle\LichessBundle\Ai\Stupid
    akismet:
        url: http://lichess.org
        #api_key: see config_local.yml

imports:
    - { resource: config_local.yml }
