imports:
    - { resource: config.yml }

framework:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

doctrine_mongo_db:
    document_managers:
        default:
            metadata_cache_driver: array

zend:
    logger:
        priority: NOTICE
        path:     %kernel.logs_dir%/%kernel.environment%.log

twig:
    auto_reload: true

lichess:
    debug_assets: true

lichess_forum:
    detect_spam: false

lichess_message:
    detect_spam: false
