imports:
    - { resource: config_dev.yml }

zend:
    logger:
        priority: ERR
        path:     %kernel.logs_dir%/%kernel.environment%.log

web_profiler:
    toolbar: false

framework:
    error_handler: false
    test: true

lichess:
    test: true
    seek:
        use_session: false
    anybody_starter:
        check_creator_is_connected: false

lichess_forum:
    detect_spam: false

doctrine_mongo_db:
    metadata_cache_driver: array
