imports:
    - { resource: config.yml }

webprofiler.config:
    toolbar: false
    intercept_redirects: false

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log

doctrine_odm.mongodb:
    metadata_cache_driver: array
    cache_driver: array
    default_database: lichess_test
