imports:
    - { resource: config.yml }

framework:
    exception_controller: LichessBundle:Main:exception

lichess:
    ai:
        crafty:
            executable_path: /usr/games/crafty

fos_comment:
    akismet:
        enabled: true
