app.config:
    charset:             UTF-8
    error_handler: null
    validation: { enabled: true, annotations: true }
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    session:
        lifetime: 2592000 # one month 
    templating:
        escaping: htmlspecialchars
        assets_version: 85
    translator: { fallback: en }

security.config:
    providers:
        doctrine_user:
            password_encoder: sha1
            entity: { class: DoctrineUserBundle:User }
    firewalls:
        public:
            pattern: .*
            form_login:
                provider:                       doctrine_user
                login_path:                     /login
                use_forward:                    false
                check_path:                     /login-check
                failure_path:                   null
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false
            logout: true
            anonymous: true

zend.config:
    logger:
        priority: notice
        path:     %kernel.logs_dir%/%kernel.environment%.log

twig.config: ~

forum.config:
    db_driver: orm
    class:
        model:
            category: Application\ForumBundle\Entity\Category
            topic: Application\ForumBundle\Entity\Topic
            post: Application\ForumBundle\Entity\Post
        controller:
            topic: Application\ForumBundle\Controller\TopicController
            post: Application\ForumBundle\Controller\PostController
        form:
            post: Application\ForumBundle\Form\PostForm
            first_post: Application\ForumBundle\Form\PostForm
        blamer:
            post: Application\ForumBundle\Blamer\PostBlamer
            topic: Application\ForumBundle\Blamer\TopicBlamer
        helper:
            forum: Application\ForumBundle\Templating\Helper\ForumHelper
    paginator:
        topics_per_page: 10
        posts_per_page: 10
        search_results_per_page: 10

doctrine_user.config:
    db_driver: orm
    class:
        model:
            user: Application\DoctrineUserBundle\Entity\User
        form:
            user: Application\DoctrineUserBundle\Form\UserForm
        controller:
            user: Application\DoctrineUserBundle\Controller\UserController
            security: Application\DoctrineUserBundle\Controller\SecurityController

time.helper: ~

lichess.config:
    ai:
        class: Bundle\LichessBundle\Ai\Crafty # also available: Bundle\LichessBundle\Ai\Stupid
