imports:
    - { resource: config.yml }

app.config:
    profiler:
        only_exceptions: false

webprofiler.config:
    toolbar: true
    intercept_redirects: false

zend.config:
    logger:
        priority: info
        path:     %kernel.logs_dir%/%kernel.environment%.log

twig.config:
    auto_reload: true

doctrine_odm.mongodb:
    metadata_cache_driver: array
    cache_driver: array
    default_database: lichess_dev
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persistent: lichess
