imports:
    - { resource: config_dev.yml }

web_profiler:
    toolbar: false

framework:
    error_handler: false
    profiler: false
    test: true

lichess:
    test: true
    seek:
        use_session: false
    anybody_starter:
        check_creator_is_active: false
    sync:
        path: ""
        latency: 0
        delay: 0.25

lichess_forum:
    detect_spam: false

doctrine_mongo_db:
    document_managers:
        default:
            metadata_cache_driver: apc
