imports:
    - { resource: config_dev.yml }

zend:
    logger:
        priority: ERR
        path:     %kernel.logs_dir%/%kernel.environment%.log

web_profiler:
    toolbar: false

framework:
    error_handler: false
    test: true

lichess:
    test: true

doctrine_mongo_db:
    metadata_cache_driver: array
    cache_driver: array
    default_database: lichess_test
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persistent: lichess
