security:
    resource: @FOSUser/Resources/config/routing/security.xml
user:
    resource: @FOSUser/Resources/config/routing.yml

lichess:
    resource: @Lichess/Resources/config/routing.yml
lichess_sync:
    resource: @Lichess/Resources/config/routing_sync.yml
lichess_translation:
    resource: @LichessTranslation/Resources/config/routing.yml
    prefix: /translation
lichess_search:
    resource: @LichessSearch/Resources/config/routing.yml
    prefix: /search

forum:
    resource: @Forum/Resources/config/routing/forum.xml
    prefix: /forum
forum_category:
    resource: @Forum/Resources/config/routing/category.xml
    prefix: /forum
forum_topic:
    resource: @Forum/Resources/config/routing/topic.xml
    prefix: /forum
forum_post:
    resource: @Forum/Resources/config/routing/post.xml
    prefix: /forum
forum_topic_show_compat:
    pattern:        /forum/{categorySlug}/{slug}/{id}.{_format}
    defaults:       { _controller: forum.controller.topic:showCompatAction, _format: "html", id: "" }
    requirements:   { _method: "get|head", _format: "html|xml", slug: "[-\w]+" }

ornicar_message:
    resource: @OrnicarMessage/Resources/config/routing.xml
    prefix: /inbox

fos_comment:
    resource: @FOSComment/Resources/config/routing.yml
