security:
    resource: UserBundle/Resources/config/routing/security.xml
user:
    resource: UserBundle/Resources/config/routing.yml

lichess:
  resource: LichessBundle/Resources/config/routing.yml

forum:
    resource: ForumBundle/Resources/config/routing/forum.xml
    prefix: /forum
forum_category:
    resource: ForumBundle/Resources/config/routing/category.xml
    prefix: /forum
forum_topic:
    resource: ForumBundle/Resources/config/routing/topic.xml
    prefix: /forum
forum_post:
    resource: ForumBundle/Resources/config/routing/post.xml
    prefix: /forum
forum_index:
    pattern:        /forum
    defaults:       { _controller: ForumBundle:Forum:index }
    requirements:   { _method: get }
forum_index2:
    pattern:        /forum/
    defaults:       { _controller: ForumBundle:Forum:index }
    requirements:   { _method: get }
forum_topic_show_compat:
    pattern:        /forum/:categorySlug/:slug/:id.:_format
    defaults:       { _controller: forum.controller.topic:showCompatAction, _format: "html", id: "" }
    requirements:   { _method: "get|head", _format: "html|xml", slug: "[-\w]+" }

ornicar_message:
    resource: MessageBundle/Resources/config/routing.xml
    prefix: /inbox
inbox:
    pattern:        /inbox
    defaults:       { _controller: MessageBundle:Message:list }
    requirements:   { _method: get }
