lichess:
  resource: LichessBundle/Resources/config/routing.yml

security:
    resource: DoctrineUserBundle/Resources/config/routing/security.xml
lichess_user:
    resource: DoctrineUserBundle/Resources/config/routing/lichess_user.yml

forum:
    resource: ForumBundle/Resources/config/routing/forum.xml
    prefix: /forum
forum_category:
    resource: ForumBundle/Resources/config/routing/category.xml
    prefix: /forum
forum_topic:
    resource: ForumBundle/Resources/config/routing/topic.xml
    prefix: /forum
forum_post:
    resource: ForumBundle/Resources/config/routing/post.xml
    prefix: /forum
forum_index:
    pattern:        /forum
    defaults:       { _controller: ForumBundle:Forum:index }
    requirements:   { _method: get }
forum_index2:
    pattern:        /forum/
    defaults:       { _controller: ForumBundle:Forum:index }
    requirements:   { _method: get }
