framework:
    secret: PYScZDvtESqkUud7
    charset:       UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enabled: false }
    form: false
    esi: false
    csrf_protection: false
    session: false
    translator: { fallback: en }

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persist: lichess
    default_database: lichess_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true
            mappings:
                LichessBundle: ~
                LichessUser:
                    type: annotation
                    dir: %kernel.root_dir%/../src/Application/UserBundle/Document
                    prefix: Application\UserBundle\Document
                FOSUser:
                    type: xml
                    dir: %kernel.root_dir%/../src/FOS/UserBundle/Resources/config/doctrine
                    prefix: FOS\UserBundle\Document

lichess:
    ai:
        crafty:
            enabled: true
            priority: 2
            executable_path: /usr/bin/crafty
            book_dir: /usr/share/crafty
        stupid:
            enabled: true
            priority: 1
    request_listener: false

imports:
    - { resource: config_local.yml }
