framework:
    secret: PYScZDvtESqkUud7
    charset:       UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enable_annotations: true }
    form: false
    csrf_protection: false
    session: false
    templating:
        engines: ['php']
    translator: { fallback: en }

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persist: lichess
    default_database: lichess_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver: apc

lichess:
    ai:
        crafty:
            enabled: true
            priority: 2
            executable_path: /usr/bin/crafty
            book_dir: /usr/share/crafty
        stupid:
            enabled: true
            priority: 1
    akismet:
        url: http://lichess.org
        #api_key: see config_local.yml

imports:
    - { resource: config_local.yml }
