imports:
    - { resource: ../../config/doctrine.yml }
    - { resource: ../../config/framework.yml }
    - { resource: ../../config/lichess.yml }

# Disable as many features as possible
framework:
    validation: { enabled: false }
    form: false
    session: false
    templating: false

# Define mappings manually
doctrine_mongodb:
    document_managers:
        default:
            auto_mapping: false
            mappings:
                LichessBundle: ~
                LichessUser:
                    type: annotation
                    dir: %kernel.root_dir%/../src/Application/UserBundle/Document
                    prefix: Application\UserBundle\Document
                FOSUser:
                    type: xml
                    dir: %kernel.root_dir%/../src/FOS/UserBundle/Resources/config/doctrine
                    prefix: FOS\UserBundle\Document

# Disable request listener
lichess:
    request_listener: false
